name: pytaste
channels:
  - defaults
dependencies:
  - backports
  - backports.lzma
  - ca-certificates
  - certifi
  - configobj
  - cycler
  - et_xmlfile
  - expat
  - freetype
  - future
  - icu
  - intel-openmp
  - jdcal
  - jpeg
  - kiwisolver
  - libiconv
  - libpng
  - libtiff
  - matplotlib
  - numpy
  - olefile
  - openpyxl
  - openssl
  - pandas=0.22
  - pcre
  - pillow
  - pip
  - pyparsing
  - pyqt
  - python=3.6
  - python-dateutil
  - pytz
  - qt
  - scipy
  - setuptools
  - sip
  - six
  - sqlite
  - tk
  - tornado
  - wheel
  - wxpython
  - xlrd
  - xz
  - zlib
  - pip:
    - json-tricks
    - pyglet
